spring:
  web:
  application:
    name: QMS
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/queue
    username: root
    password: p@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8083
token:
  signing:
    key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  refresh:
    token:
      expiration: 1800000
    signing:
      key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  access:
    token:
      expiration: 1800000 # Set the expiration time for the access token in milliseconds (e.g., 1 hour)

queue:
  name: ticket-queue