version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      start_period: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - queue_network

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: queue
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - queue_network
    volumes:
      - db_data:/var/lib/mysql

  queue:
    image: "manite/queue-service-img:s1"
    container_name: queue_service
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/queue
    networks:
      - queue_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s

  ui:
    image: "manite/queue-ui:s1"
    container_name: queue-ui
    ports:
      - "4200:80"
    networks:
      - queue_network

volumes:
  rabbitmq_data:
  db_data:

networks:
  queue_network:
    driver: "bridge"
